### ISSUE TITLE
Cpp miscompilation when using mutable arguments

### ISSUE THREAD

**Issue by truelossless** [tracel-ai/cubecl#447]
Hello,

Thanks for the great work on CubeCL!
I've noticed that using mutable arguments on a `#[cube]` kernel causes a cpp miscompilation while using CUDA as the backend.

Example code:

This cube function...

```rust
#[cube]
pub fn foo(mut idx: u64) -> u64 {
    idx += 1;
    idx
}
```
...compiles to...
```c
const uint64 l_2 = output_0[idxGlobal];
const uint64 l_2 = l_2 + uint64(1);
output_0[idxGlobal] = l_2;
```
...which causes
```
    default_program(23): error: "l_2" has already been declared in the current scope
      const uint64 l_2 = l_2 + uint64(1);
                   ^
    default_program(23): warning #549-D: variable "l_2" is used before its value is set
      const uint64 l_2 = l_2 + uint64(1);
                         ^
    Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"
    default_program(22): warning #177-D: variable "l_2" was declared but never referenced
      const uint64 l_2 = output_0[idxGlobal];
                   ^
    1 error detected in the compilation of "default_program".
```

Copying the argument in the function instead of mutating it works fine:
```rust
#[cube]
pub fn foo(idx: u64) -> u64 {
    let mut idx2 = idx;
    idx2 += 1;
    idx2
}
```

**Comment by clarin-ebtio800090** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the KernelParam struct and its implementation to handle mutable arguments correctly. This change prevents the miscompilation issue when using mutable arguments in CUDA kernels.

You can review changes in this commit: https://github.com/clarin-ebtio800090/tracel-ai-cubecl-447/commit/17d4679e3fa5bd86670bd557a581b81423ab9e2a.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by maxtremblay** [comment]
Can you validate if you are running the latest version of cubecl? I fixed a bunch of these lately.

**Comment by truelossless** [comment]
Yes, it still happens in #a43015e2.
I haven't tested it toroughly, but I think variable shadowing can miscompile too.

**Comment by nathanielsimard** [comment]
I don't think we parse mutability correctly in CubeCL yet. It's because there is comptime mutability (which we handle correctly), referring to the manipulation of symbols at compile time, and "real" mutability, which involves actually changing a register's value at runtime. For now, you can use `let mut variable = variable.runtime()` to declare the latter.
